version: '3'
services:
  jupyter:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'dscontainer'
    entrypoint: >
      jupyter-lab --ip=0.0.0.0 --allow-root --port=8888 --no-browser --NotebookApp.token='' --notebook-dir='/root/src'
    ports:
      - '8888:8888'
    working_dir: '/root/src'
    tty: true
    # ホスト側のディレクトリをコンテナ側にマウントする．
    # マウントされたディレクトリは更新するとコンテナ側にも反映される．
    volumes:
      - ./src:/root/src

# docker-compose buildでイメージを作成する ※docker-compose.yml，Dockerfile，requirements.txtを変更した場合
# docker-compose up -dでコンテナを起動する
# docker imagesでイメージを確認する
# docker-compose psでコンテナを確認する
# docker exec -it dscontainer [command]でコンテナ内でコマンドを実行する
# docker exec -it dscontainer bashでコンテナのプロンプトに入る

# 停止は docker-compose stop
# 停止したものの起動は docker-compose start
# コンテナの削除は docker-compose down
# コンテナの再起動は docker-compose restart

# 参考
# https://tekkubu.com/docker-jupyter-lab/#index_id2
# https://qiita.com/tay2501/items/1f82f16447bdff86247d#fn1
# https://zuma-lab.com/posts/docker-python-settings